# Generated by Django 5.1.4 on 2024-12-11 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmirecord',
            old_name='average_stool',
            new_name='daily_stool',
        ),
        migrations.RenameField(
            model_name='bmirecord',
            old_name='oxygen_levels',
            new_name='water_intake',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='age',
        ),
        migrations.RemoveField(
            model_name='bmirecord',
            name='bmi',
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='glycerol_level',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='bmirecord',
            name='oxygen_level',
            field=models.FloatField(default=95.0),
        ),
        migrations.AlterField(
            model_name='bmirecord',
            name='astronaut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bmirecord',
            name='calorie_intake',
            field=models.FloatField(),
        ),
    ]
