# Generated by Django 5.1.4 on 2024-12-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0002_rename_average_stool_bmirecord_daily_stool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmirecord',
            name='water_intake',
            field=models.FloatField(default=2000.0),
        ),
    ]
