# Generated by Django 5.1.4 on 2024-12-12 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0003_alter_bmirecord_water_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='astronauts', to=settings.AUTH_USER_MODEL),
        ),
    ]
