# Generated by Django 5.1.4 on 2024-12-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0004_alter_astronaut_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmirecord',
            name='bmi',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
